// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAim2eaqsOeeTYV4F1LbQCT9JaNPYAsw0c',
    appId: '1:441573073881:web:9fda91d1ec3ace5d066fc8',
    messagingSenderId: '441573073881',
    projectId: 'blackmarket-48540',
    authDomain: 'blackmarket-48540.firebaseapp.com',
    databaseURL: 'https://blackmarket-48540-default-rtdb.firebaseio.com',
    storageBucket: 'blackmarket-48540.appspot.com',
    measurementId: 'G-LDV1Y9MPPK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBUHnnZPizPKNmsWXM9IGheJOXjO4O3JBA',
    appId: '1:441573073881:android:0cd9082e185c1bea066fc8',
    messagingSenderId: '441573073881',
    projectId: 'blackmarket-48540',
    databaseURL: 'https://blackmarket-48540-default-rtdb.firebaseio.com',
    storageBucket: 'blackmarket-48540.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCV00KL5lhS47SMV0ld0wJftqKJzf_TSXc',
    appId: '1:441573073881:ios:3a331d2b5286d6a0066fc8',
    messagingSenderId: '441573073881',
    projectId: 'blackmarket-48540',
    databaseURL: 'https://blackmarket-48540-default-rtdb.firebaseio.com',
    storageBucket: 'blackmarket-48540.appspot.com',
    iosClientId: '441573073881-praeefcc2o5e0l17eb4frannqflqeqn8.apps.googleusercontent.com',
    iosBundleId: 'com.kskilstudio.blackMarket',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCV00KL5lhS47SMV0ld0wJftqKJzf_TSXc',
    appId: '1:441573073881:ios:3a331d2b5286d6a0066fc8',
    messagingSenderId: '441573073881',
    projectId: 'blackmarket-48540',
    databaseURL: 'https://blackmarket-48540-default-rtdb.firebaseio.com',
    storageBucket: 'blackmarket-48540.appspot.com',
    iosClientId: '441573073881-praeefcc2o5e0l17eb4frannqflqeqn8.apps.googleusercontent.com',
    iosBundleId: 'com.kskilstudio.blackMarket',
  );
}
